config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  # get 'contacts_error_log/index'
  resources :contact_errors, controller: 'contacts_error_log', only: :index
  resources :contacts, only: %i[index]

  # TODO: refactor this routes controller it can be better routes
  resources :contact_importer, only: %i[index new create]

  devise_for :users
  root 'contact_importer#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  belongs_to :contact_info_csv, optional: true
  validates  :name, :dob, :phone, :address, :cc, :franchise, :email, presence: true
  validates :name, format: { with: /\A[A-Za-z\- ]+\Z/ }
  validates :phone, format: { with: /\(\+\d{2}\) \d{3}(-| )\d{3}(-| )\d{2}(-| )\d{2}\Z/ }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :email, uniqueness: { scope: :user_id }
end

app/models/contact_info_csv.rb
class ContactInfoCsv < ApplicationRecord
  include AASM

  aasm column: 'status' do
    state :on_hold, initial: true
    state :processing, :failed, :finished

    event :mark_processing do
      transitions from: %i[on_hold processing], to: :processing
    end

    event :mark_failed do
      transitions from: :processing, to: :failed
    end

    event :mark_finished do
      transitions from: :processing, to: :finished
    end
  end
  belongs_to :user
  has_one_attached :csv
  validates :csv, presence: true, blob: { content_type: /csv/i }
  store_accessor :row_config, :name, :dob, :phone, :address, :cc, :franchise, :email
  after_create :create_job
  before_create :row_config_adjustment

  # TODO: use translations
  ROW_CONFIG_NAME_MAPPING = {
    name: 'Name',
    dob: 'Date of Birth',
    phone: 'Phone Number',
    address: 'Address',
    cc: 'Credit Card',
    franchise: 'Franchise',
    email: 'Email'
  }.freeze

  PERMITED_PARAMS = ROW_CONFIG_NAME_MAPPING.keys.append(:csv).freeze

  private

  def row_config_adjustment
    row_config.transform_values! { |v| v.to_i - 1 }
  end

  def create_job
    CreateContactsWorker.perform_in(5.minutes, id)
  end
end

app/models/contacts_error_log.rb
class ContactsErrorLog < ApplicationRecord
  belongs_to :user

  NAME_MAPPING = {
    row: 'Row with errors',
    file_name: 'File',
    log_message: 'Error Message'
  }.freeze
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :rememberable

  has_many :contact_files, class_name: 'ContactInfoCsv', foreign_key: 'user_id'
  has_many :contacts
  has_many :contacts_error_logs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/contact_importer_controller.rb
# frozen_string_literal: true

# Controller to handle all importer CSV
class ContactImporterController < ApplicationController
  before_action :authenticate_user!

  def new
    @contact_info = ContactInfoCsv.new
  end

  def index
    @pagy, @files = pagy(current_user.contact_files, items: 5)
  end

  def create
    current_user.contact_files.create!(permitted_contacts_params)
    redirect_to root_path, notice: 'File Uploaded!'
  rescue StandardError
    flash[:error] = I18n.t(:uplad_csv_error)
    redirect_to root_path
  end

  private

  def permitted_contacts_params
    params.require(:contact_info_csv).permit(ContactInfoCsv::PERMITED_PARAMS)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  def index
    @pagy, @contacts = pagy(current_user.contacts, items: 5)
  end
end

app/controllers/contacts_error_log_controller.rb
class ContactsErrorLogController < ApplicationController
  before_action :authenticate_user!
  def index
    @pagy, @logs = pagy(current_user.contacts_error_logs, items: 5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/importer_helper.rb
module ImporterHelper
end

app/views/contact_importer/index.html.erb
<h1 class="bg-warning text-white text-center">Contact Files</h1>
<%= render 'shared/flash_messages' %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Imported File name</th>
      <th scope="col">Row Mapping</th>
      <th scope="col">Status</th>
      <th scope="col">Download</th>
    </tr>
  </thead>
  <tbody>
    <% @files.each do |file| %>
    <tr>
      <td><%= file.csv.attached? ? file.csv.filename : 'File Not Found' %></td>
      <td>
        <pre><%= file.row_config.transform_values{ |v| v.to_i + 1 }.to_json %></pre>
      </td>
      <td><%= file.status.titleize %></td>
      <td><a href="<%= file.csv.attached? ? file.csv.url : 'file not found'%>">Download</a></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%== pagy_nav(@pagy) %>

app/views/contact_importer/new.html.erb
<h1 class="bg-warning text-white text-center">Import contacts</h1>
<%= render 'shared/flash_messages' %>

<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <h3>Impor Csv file</h3>
      <h5> Instructions </h5>
      <p></p>
    </div>
    <div class="col-sm-6">
      <div class="row mb-2">
        <%= form_for(@contact_info, url: contact_importer_index_path, method: :post) do |f| %>
          <div class="row">
            <span class="mb-2 mt-2"> CSV File:  </span>
            <%= f.file_field :csv, class: 'col-sm-12' %>
          </div>
          <div class="row">
            <span class="mb-2 mt-2"> CSV ROW configuration:  </span>
            <% ContactInfoCsv::ROW_CONFIG_NAME_MAPPING.each do |key, label| %>
              <div class="row">
                <%= f.label label %>
                <%= f.number_field key %>
              </div>
            <% end %>
          </div>
        </div>
        <%= f.submit 'Submit' %>
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/index.html.erb
<h1 class="bg-warning text-white text-center">Contacts</h1>
<%= render 'shared/flash_messages' %>
<table class="table">
  <thead>
    <tr>
      <% ContactInfoCsv::ROW_CONFIG_NAME_MAPPING.each do |key, label|%>
        <th scope="col"><%= label %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <% ContactInfoCsv::ROW_CONFIG_NAME_MAPPING.each do |key, label|%>
          <td><%= contact.try(key) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%== pagy_nav(@pagy) %>

app/views/contacts_error_log/index.html.erb
<h1 class="bg-danger text-white text-center">Contact Error Logs</h1>
<%= render 'shared/flash_messages' %>
<table class="table">
  <thead>
    <tr>
      <% ContactsErrorLog::NAME_MAPPING.each do |key, label|%>
        <th scope="col"><%= label %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @logs.each do |contact| %>
      <tr>
        <% ContactsErrorLog::NAME_MAPPING.each do |key, label|%>
          <td><%= contact.try(key) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%== pagy_nav(@pagy) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html translate="no">
  <head>
    <meta name="google" content="notranslate">
    <title>ContactInfoProcessing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' if current_user.present? %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<div class="mb-2">
  <% flash.each do |type, msg| %>
    <div class="<%= type.include?('error') ? 'bg-danger' : 'bg-info' %> text-center text-white">
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">ContactAppNavbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item m-1">
        <%= link_to "Contacts", contacts_path %>
      </li>
      <li class="nav-item m-1">
        <%= link_to "Contact Errors", contact_errors_path %>
      </li>
      <li class="nav-item m-1">
        <%= link_to "Contacts Files", contact_importer_index_path %>
      </li>
      <li class="nav-item m-1">
        <%= link_to "Import Contacts", new_contact_importer_path %>
      </li>
    </ul>
  </div>
</nav>